services:
  - type: web
    name: the-green
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true 