services:
  - type: web
    name: the-green
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /
    autoDeploy: true 